%
% IV - Interactive Image Viewer
% 
% An interactive image viewer tool for a matlab
% array (iv_pic) that has been prepared by the user.
% The tool allows display of ABS, REAL, IMAG, and
% PHASE parts of the data with a variety of functions:
%
% WINDOW/CENTER
% ZOOM & PAN
% HARDCOPY
% HORIZONTAL & VERTICAL TRACE DISPLAY
% HORIZONTAL & VERTICAL MAXIMUM INTENSITY PROJECTION
% HORIZONTAL & VERTICAL MINMIUM INTENSITY PROJECTION
% HORIZONTAL & VERTICAL SUM PROJECTION
% LOG/LINEAR DISPLAY SCALE
%
%
% INPUTS
%
% iv_pic      A 2D array of image points for viewing
%
% $Id: iv.m,v 1.1 2007/11/26 21:52:17 dfoxall Exp $
%
%---------------------------------------------------------


%---------------------------------------------------------
% CONTROL INDICES
%---------------------------------------------------------

PRINTER      = 'postscript';
ON           = 'on';
OFF          = 'off';

IMAGE_WINDOW = 1;
IMAGE_CENTER = 2;
IMAGE_ZOOM   = 3;
IMAGE_DISP   = 4;
IMAGE_MODE   = 5;
IMAGE_PRINT  = 9;
IMAGE_QUIT   = 10;

PROJ_VLOC    = 11; 
PROJ_HLOC    = 12; 
PROJ_HMODE   = 13;
PROJ_VMODE   = 14;



%---------------------------------------------------------
% CONTROL LABELS
%---------------------------------------------------------

cont_lbl = { 'WINDOW',          'CENTER',           'label 3',              'IMAGE DISPLAY', ...
             'IMAGE MODE',      'label 6',          'label 7',              'label 8', ...
             'label 9',         'QUIT',             'HORIZONTAL CURSOR',    'VERTICAL CURSOR', ...
             'VERTICAL MODE',   'HORIZONTAL MODE',  'label 15',             'label 16', ...
             'label 17',        'label 18',         'label 19',             'label 20'
            };


%---------------------------------------------------------
% CONTROL STYLES
%---------------------------------------------------------

cont_style = { 'slider',     'slider',     'text',           'listbox', ...
               'listbox',    'text',       'text',           'text', ...
               'text',       'pushbutton', 'slider',         'slider', ...
               'listbox',    'listbox',    'text',           'text', ...
               'text',       'text',       'text',           'text'  
             };


%---------------------------------------------------------
% CONTROL VISIBLE
%---------------------------------------------------------

cont_vis = { 'on',    'on',    'off',  'on',  ... 
             'on',    'off',   'off',  'off', ... 
             'off',    'on',    'on',   'on',  ... 
             'on',    'on',    'off',  'off', ... 
             'off',   'off',   'off',  'off' 
           };



%---------------------------------------------------------
% IMAGE DISPLAY CALLBACK
%---------------------------------------------------------

display_image = [ '     '                                           ...
                  'vloc = get(cont_wid_hdl(PROJ_VLOC),''Value'');'  ...
                  'hloc = get(cont_wid_hdl(PROJ_HLOC),''Value'');'  ...
                  'vpos = round(vsize*vloc);'                       ...
                  'hpos = round(hsize*hloc);'                       ...
                  '     '                                           ...
                  'if (vpos < 1)    '                               ...
                  'vpos = 1;'                                       ...
		  'end;'                                            ...
                  '     '                                           ...
                  'if (vpos > vsize )    '                          ...
                  'vpos = vsize;'                                   ...
		  'end;'                                            ...
                  '     '                                           ...
                  'if (hpos < 1)    '                               ...
                  'hpos = 1;'                                       ...
		  'end;'                                            ...
                  '     '                                           ...
                  'if (hpos > hsize )    '                          ...
                  'hpos = hsize;'                                   ...
		  'end;'                                            ...
                  '     '                                           ...
                  'vtil = sprintf(''HORIZONTAL TRACE = %d'',vpos);' ...
                  'htil = sprintf(''VERTICAL TRACE = %d  '',hpos);' ...
                  '     '                                           ...
                  'mode = get(cont_wid_hdl(IMAGE_DISP),''Value'');' ...
                  '     '                                           ...
                  'if (mode == 1) '                                 ...
                  'iv_disp_data = abs(iv_pic);'                     ...
                  'end;'                                            ...
                  '     '                                           ...
                  'if (mode == 2) '                                 ...
                  'iv_disp_data = real(iv_pic);'                    ...
                  'end;'                                            ...
                  '     '                                           ...
                  'if (mode == 3) '                                 ...
                  'iv_disp_data = imag(iv_pic);'                    ...
                  'end;'                                            ...
                  '     '                                           ...
                  'if (mode == 4) '                                 ...
                  'iv_disp_data = angle(iv_pic);'                   ...
                  'end;'                                            ...
                  '     '                                           ...
                  'mode = get(cont_wid_hdl(IMAGE_MODE),''Value'');' ...
                  '     '                                           ...
                  'if (mode == 2) '                                 ...
                  'temp_data=log(abs(iv_disp_data)+1);'             ...
                  'iv_disp_data = temp_data;'                       ...
                  'end;'                                            ...
                  '     '                                           ...
                  'mode = get(cont_wid_hdl(PROJ_HMODE),''Value'');' ...
                  '     '                                           ...
                  'if (mode == 1) '                                 ...
                  'iv_hproj_data = iv_disp_data(:,hpos);'           ...
                  'end;'                                            ...
                  '     '                                           ...
                  'if (mode == 2) '                                 ...
                  'iv_hproj_data = max(transpose(iv_disp_data));'   ...
                  'htil = ''VERTICAL MAX INTENSITY PROJECTION'';'   ...
                  'end;'                                            ...
                  '     '                                           ...
                  'if (mode == 3) '                                 ...
                  'iv_hproj_data = min(transpose(iv_disp_data));'   ...
                  'htil = ''VERTICAL MIN INTENSITY PROJECTION'';'   ...
                  'end;'                                            ...
                  '     '                                           ...
                  'if (mode == 4) '                                 ...
                  'iv_hproj_data = sum(transpose(iv_disp_data));'   ...
                  'htil = ''VERTICAL SUM INTENSITY PROJECTION'';'   ...
                  'end;'                                            ...
                  '     '                                           ...
                  'mode = get(cont_wid_hdl(PROJ_VMODE),''Value'');' ...
                  '     '                                           ...
                  'if (mode == 1) '                                 ...
                  'iv_vproj_data = iv_disp_data(vpos,:);'           ...
                  'end;'                                            ...
                  '     '                                           ...
                  'if (mode == 2) '                                 ...
                  'iv_vproj_data = max(iv_disp_data);'              ...
                  'vtil = ''HORIZONTAL MAX INTENSITY PROJECTION'';' ...
                  'end;'                                            ...
                  '     '                                           ...
                  'if (mode == 3) '                                 ...
                  'iv_vproj_data = min(iv_disp_data);'              ...
                  'vtil = ''HORIZONTAL MIN INTENSITY PROJECTION'';' ...
                  'end;'                                            ...
                  '     '                                           ...
                  'if (mode == 4) '                                 ...
                  'iv_vproj_data = sum(iv_disp_data);'              ...
                  'vtil = ''HORIZONTAL SUM INTENSITY PROJECTION'';' ...
                  'end;'                                            ...
                  '     '                                           ...
                  'imw=get(cont_wid_hdl(IMAGE_WINDOW),''Value'');'  ...
		  'imc=get(cont_wid_hdl(IMAGE_CENTER),''Value'');'  ...
                  'ims= max(max(iv_disp_data));'                    ...
                  'temp_data = imc+(imw/ims)*iv_disp_data;'         ...
                  'view_data = temp_data;'                          ...  
                  '     '                                           ...
                  'view_data(vpos,:)   = vcursor;'                  ...               
                  'view_data(:,hpos)   = hcursor;'                  ...               
                  '     '                                           ...
                  'eval(update_display);'                           ...               
                ];

update_display = [ 'subplot(image_plt);'                                             ...
                   'image(view_data);'                                               ...
                   'axis(''image'');'                                                ... 
                   'colormap(gray(256));'                                            ... 
                   'mode = get(cont_wid_hdl(IMAGE_ZOOM),''Value'');'                 ...
                   '     '                                                           ...
                   'if (mode == 1) '                                                 ...
                   'zoom(image_plt,ON);'                                             ... 
                   'else '                                                           ...
                   'zoom(image_plt,OFF);'                                            ... 
                   'end;'                                                            ...
                   '     '                                                           ...
                   'subplot(vproj_plt);'                                             ...
                   'plot(iv_vproj_data);'                                            ...
                   'title(vtil);'                                                    ...
                   'grid;'                                                           ...
                   '     '                                                           ...
                   'subplot(hproj_plt);'                                             ...
                   'plot(iv_hproj_data);'                                            ...
                   'title(htil);'                                                    ...
                   'grid;'                                                           ...
                   '     '                                                           ...
                   'subplot(image_plt);'                                             ...
                 ]; 


hardcopy     =   [ '        '                                        ...
                   'capture(disp_hdl);'                              ...
                   'print plot -deps;'                               ...
                   'unix_cmd = [''lpr -P'',PRINTER,'' plot.eps''];'  ...
                   'unix(unix_cmd);'                                 ...
                   'close;'                                          ...
                 ];


quit_program =   [ '        '                                        ...
                   'close(disp_hdl);'                                ...
                 ];



%---------------------------------------------------------
% DISPLAY FIGURE WINDOW & AXES
%---------------------------------------------------------

disp_H    = 200;
disp_V    = 150;
disp_X    = 800;
disp_Y    = 800;
disp_loc  = [disp_H,disp_V,disp_X,disp_Y];
disp_hdl  = figure('position',disp_loc,                ...
                   'MenuBar','none',                   ...
                   'Name','Image Viewer',              ...
                   'NumberTitle','off'                 ...
                   );

image_plt = subplot('position',[0.05,0.5,0.45,0.45]); 
vproj_plt = subplot('position',[0.55,0.8,0.4,0.15]); 
hproj_plt = subplot('position',[0.55,0.55,0.4,0.15]); 




%---------------------------------------------------------
% CONTROL PANEL LABEL FIELDS
%---------------------------------------------------------
cont_N       = length(cont_lbl);
cont_cols    = 2;
cont_rows    = cont_N/cont_cols;

cont_lbl_X   = 180;
cont_lbl_Y   = 20;
cont_margin  = 10;
cont_width   = 400; 
cont_hite    = 350;

for I = 1:cont_cols

    cont_lbl_H = cont_margin + (I-1)*cont_width;
  

    for J=1:cont_rows

        K                = (I-1)*cont_rows + J;
        cont_lbl_V       = cont_hite + cont_margin - J*(cont_margin+cont_lbl_Y) ;
        cont_lbl_loc     = [cont_lbl_H,cont_lbl_V,cont_lbl_X,cont_lbl_Y];

        cont_lbl_hdl(K)  = uicontrol( 'Style',     'text',         ...
                                      'Position',  cont_lbl_loc,   ...
                                      'string',    cont_lbl(K),    ...
                                      'Visible',   char(cont_vis(K))  ...
                                    );
    end

end


%---------------------------------------------------------
% CONTROL PANEL WIDGETS
%---------------------------------------------------------
cont_wid_X = 200;
cont_wid_Y = 20;
wc_max     = 256.0;

for I = 1:cont_cols

    cont_wid_H = cont_margin + cont_lbl_X + (I-1)*cont_width;
  

    for J=1:cont_rows

        K                = (I-1)*cont_rows + J;
        cont_wid_V       = cont_hite + cont_margin - J*(cont_margin+cont_wid_Y) ;
        cont_wid_loc     = [cont_wid_H,cont_wid_V,cont_wid_X,cont_wid_Y];
        local_style      = char(cont_style(K));

        cont_wid_hdl(K)  = uicontrol( 'Style',     local_style,           ...
                                      'Position',  cont_wid_loc,          ...
                                      'Visible',   char(cont_vis(K))      ...
                                    );
    end

end



set(cont_wid_hdl(IMAGE_WINDOW),'min',0.0,'max',wc_max','value',wc_max,'callback',display_image);
set(cont_wid_hdl(IMAGE_CENTER),'min',0.0,'max',wc_max','value',0.0,'callback',display_image);
%set(cont_wid_hdl(IMAGE_ZOOM),'callback',display_image);
set(cont_wid_hdl(IMAGE_DISP),'string',{'ABS','REAL','IMAGINARY','PHASE'},'callback',display_image);
set(cont_wid_hdl(IMAGE_MODE),'string',{'LINEAR','LOG'},'callback',display_image);
%set(cont_wid_hdl(IMAGE_PRINT),'string','PRINT','callback',hardcopy);
set(cont_wid_hdl(IMAGE_QUIT),'string','EXIT','callback',quit_program);


set(cont_wid_hdl(PROJ_VLOC),'min',0.0,'max',1.0,'value',0.5,'callback',display_image);
set(cont_wid_hdl(PROJ_HLOC),'min',0.0,'max',1.0,'value',0.5,'callback',display_image);
set(cont_wid_hdl(PROJ_HMODE),'string',{'TRACE','MAX-IP','MIN-IP','SUM'},'callback',display_image);
set(cont_wid_hdl(PROJ_VMODE),'string',{'TRACE','MAX-IP','MIN-IP','SUM'},'callback',display_image);



%---------------------------------------------------------
% INITIALIZE
%---------------------------------------------------------
[vsize,hsize]    = size(iv_pic); 
hcursor          = zeros(1,hsize);
vcursor          = zeros(vsize,1);
hcursor          = wc_max*mod(cumsum(ones(vsize,1)),2);
vcursor          = wc_max*mod(cumsum(ones(1,hsize)),2);
iv_disp_data     = iv_pic;

eval(display_image);

