
comment_info_spec = { ...
'# Scan name   :'                    'char  scalar' 'scan_name'; ... 
'# Dataset name:'                    'char  scalar' 'dataset_name'; ...
'# Gyroscan SW release            :' 'char  scalar' 'gyroscan_release'; ...
'# Reconstruction Host SW Version :' 'int   scalar' 'reconstruction_host_version'; ...
'# Reconstruction   AP SW Version :' 'int   scalar' 'reconstruction_ap_version'; ...
};


geninfo_spec = { ... 
'.    0    0    0  number_of_mixes                    :' 'int   scalar' 'number_of_mixes'; ...
'.    0    0    0  number_of_encoding_dimensions      :' 'int   scalar' 'number_of_encoding_dimensions'; ...
'.    0    0    0  number_of_dynamic_scans            :' 'int   scalar' 'number_of_dynamic_scans'; ...
'.    0    0    0  number_of_cardiac_phases           :' 'int   scalar' 'number_of_cardiac_phases'; ...
'.    0    0    0  number_of_echoes                   :' 'int   scalar' 'number_of_echoes'; ...
'.    0    0    0  number_of_locations                :' 'int   scalar' 'number_of_locations'; ...
'.    0    0    0  number_of_extra_attribute_1_values :' 'int   scalar' 'number_of_extra_attribute_1_values'; ...
'.    0    0    0  number_of_extra_attribute_2_values :' 'int   scalar' 'number_of_extra_attribute_2_values'; ...
'.    0    0    0  number_of_signal_averages          :' 'int   scalar' 'number_of_signal_averages'; ...
'.    0    0    0  number_of_gradient_echoes          :' 'int   scalar' 'number_of_gradient_echoes'; ...
'.    0    0    0  kx_range                           :' 'int   vector' 'kx_range'; ...
'.    0    0    0  ky_range                           :' 'int   vector' 'ky_range'; ...
'.    0    0    0  kx_oversample_factor               :' 'float scalar' 'kx_oversample_factor'; ...
'.    0    0    0  ky_oversample_factor               :' 'float scalar' 'ky_oversample_factor'; ...
'.    0    0    0  X-resolution                       :' 'int   scalar' 'X_resolution'; ...
'.    0    0    0  Y-resolution                       :' 'int   scalar' 'Y_resolution'; ...
'.    0    0    0  X_range                            :' 'int   vector' 'X_range'; ...
'.    0    0    0  Y_range                            :' 'int   vector' 'Y_range'; ...
};
